### ISSUE TITLE
Polyglot

### ISSUE THREAD

**Issue by lainq** [SurPathHub/showcase-your-project#3]
Project Name: Polyglot
Project Link: https://github.com/pranavbaburaj/polyglot
Project Logo: 
![logo](https://user-images.githubusercontent.com/70764593/114295267-c9cdb780-9ac1-11eb-94aa-f864328d6845.png)
Tools: Visual Studio Code
Languages: Python

**Comment by vinzvinci** [comment]
Looks good @pranavbaburaj 👍 I'll add this later

**Comment by lainq** [comment]
Thank you

**Comment by vinzvinci** [comment]
Hi, thank you for submitting your project. We just made a discussion that we will use this repository for our current event. Sorry, but we can't add the project this time. I would like to introduce our project next time and would love to collaborate with you. I will put this issue **on hold**, which means you may receive a notification soon.

Thank you!
