### ISSUE TITLE
Reseter.css

### ISSUE THREAD

**Issue by ghost** [SurPathHub/showcase-your-project#4]
Project Name: Reseter.css
Project Link: https://github.com/krishdevdb/reseter.css
Project Logo: ![](https://github.com/krishdevdb/reseter.css/raw/master/logo.png)
Tools: Visual Studio Code
Languages: CSS, Sass, Scss, Less, Stylus, JavaScript, TypeScript

**Comment by vinzvinci** [comment]
Awesome, thank you @krishdevdb. I will add this soon :)

**Comment by vinzvinci** [comment]
Hi, thank you for submitting your project. We just made a discussion that we will use this repository for our current event. Sorry, but we can't add the project this time. I would like to introduce our project next time and would love to collaborate with you. I will put this issue **on hold**, which means you may receive a notification soon.

Thank you!
