### ISSUE TITLE
Ryjin210

### ISSUE THREAD

**Issue by Ryjin210** [SurPathHub/showcase-your-project#5]
**Project Name:**
TechGeeksHub Website

**Repository Link:** 
https://github.com/Ryjin210/TechGeeksHub

**Tools:**
Visual Studio Code, Adobe Illustrator, Adobe Photoshop

**Languages:**
HTML, CSS, Javascript, Bootstrap

**Comment by vinzvinci** [comment]
Do you have a plan to host this on github-pages?

**Comment by vinzvinci** [comment]
Congrats for completing this 🎉 Please check your dm on discord.
