### ISSUE TITLE
lexus654

### ISSUE THREAD

**Issue by lexus654** [SurPathHub/showcase-your-project#6]
**Project Name:**
Math All You Can
**Repository Link:** 
https://github.com/lexus654/MathAllYouCan
**Tools:**
VS CODE, FIGMA, REACT DEV TOOL, GOOGLE CHROME
**Languages:**
Javascript, ReactJS, HTML, CSS, Styled Components

**Comment by vinzvinci** [comment]
Page not found 🤔

**Comment by vinzvinci** [comment]
works now, thanks

**Comment by vinzvinci** [comment]
Congrats for completing this 🎉 Please check your dm on discord.
